@file:Suppress("PackageDirectoryMismatch")

object Versions {
    const val gradleVersion = "8.0.0-alpha08"
    const val kotlinVersion = "1.7.0"
    const val daggerHiltVersion = "2.44.2"
    const val hiltVersion = "1.0.0"
    const val kotlinCompilerExtensionVersion = "1.2.0"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "5.0.0-alpha.3"
    const val truthVersion = "1.1.3"
    const val coreKtxVersion = "1.9.0"
    const val materialIconsVersion = "1.2.0"
    const val junit4Version = "4.13.2"
    const val junitExtensionsVersion = "1.1.4"
    const val espressoCoreVersion = "3.5.0"
    const val mockkVersion = "1.13.2"
    const val androidArchCoreTest = "2.1.0"
    const val testMonitorVersion = "1.2.0"
    const val testRunnerVersion = "1.5.1"
    const val composeVersion = "1.2.0"
    const val composeActivityVersion = "1.6.1"
    const val livedataKtxVersion = "2.5.1"
    const val composeViewModelVersion = "2.5.1"
    const val composeConstraintLayoutVersion = "1.0.1"
    const val hiltNavigationCompose = "1.0.0"
    const val accompanistSwipeRefresh = "0.27.1"
    const val coroutinesVersion = "1.6.4"
    const val roomVersion = "2.4.3"
    const val lifecycleRuntimeVersion = "2.5.1"
    const val coreDesugarVersion = "2.0.0"
    const val locationServicesVersion = "21.0.1"
    const val stethoVersion = "1.6.0"
    const val datastoreVersion = "1.0.0"
    const val logcatVersion = "0.1"
    const val combineTupleVersion = "1.1.1"
    const val testManifestVersion = "1.2.0"
}
