#name: Deploy to Google Play Store
#
#on:
#  push:
#    tags:
#      - v*
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: 17
#          distribution: 'temurin'
#
#      - name: Grant execute permissions for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Cache Gradle dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Build Android App Release
#        run: ./gradlew assembleRelease --stacktrace
#
#      - name: Sign APK
#        id: sign_apk
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
#          alias: ${{ secrets.KEY_ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#
#      - name: Create release
#        uses: actions/create-release@v1
#        if: startsWith(github.ref, 'refs/tags/v')
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false
#
#      - name: Build changelog for release
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@v3
#        with:
#          configurationJson: |
#            {
#              "template": "Changes:\n#{{UNCATEGORIZED}}",
#              "pr_template": "#{{TITLE}} ##{{NUMBER}}",
#              "trim_values": true,
#            }
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Create changelog folder for release
#        run: mkdir playwhatsnew
#
#      - name: Write changelog for release
#        run: echo '${{ steps.build_changelog.outputs.changelog }}' > playwhatsnew/whatsnew-en-US
#
#      - name: Release to Google Play Store
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
#          packageName: com.lyvetech.cloudy
#          releaseFile: ${{ steps.sign_apk.outputs.signedReleaseFile }}
#          track: production
#          inAppUpdatePriority: 0
#          whatsNewDirectory: playwhatsnew